export const STEPS: Record<string, number> = {
  BOOK_QR_CODE_SCANNING: 0,
  BOOK_CONFIRMATION: 1,
  PENDING_RETURN_LISTING: 2,
  SHELF_QR_CODE_SCANNING: 3,
  LOADING: 4,
  BOOK_NOT_FOUND: 5,
  SHELF_NOT_FOUND: 6,
  SUCCESS: 7,
  ERROR: 8,
};
