export const STEPS: Record<string, number> = {
  BOOK_QR_CODE_SCANNING: 0,
  BOOK_CONFIRMATION: 1,
  PENDING_RETURN_LISTING: 2,
  SHELF_QR_CODE_SCANNING: 3,
  SHELF_CONFIRMATION: 4,
  LOADING: 5,
  BOOK_NOT_FOUND: 6,
  SHELF_NOT_FOUND: 7,
  SUCCESS: 8,
  ERROR: 9,
};
